services:
  database:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-dbest_moon}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-example}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  app:
    image: dbest-moon/app:latest
    restart: always
    build:
      context: .
    depends_on:
      - database
    ports:
      - ${WEB_PORT:-3000}:3000
      - ${API_PORT:-8080}:8080
    environment:
      WEB_PORT: 3000
      API_PORT: 8080
      DB_NAME: ${DB_NAME:-dbest_moon}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-example}
      DB_HOST: database
      DB_PORT: 5432
    volumes:
      - ./data/drizzle:/app/apps/api/drizzle
